language: perl
perl:
  - "5.10"
  - "5.16"
  - "5.20"
notifications:
  slack:
    secure: k2FZkFwzAuxsxu45IHAhtIcBJeV0GYBBo/gkLGlFyM79sIdwn/YvV4wztSaBXeSn6Qo/ovcTksAOmUMY0MzF0Kf7ruvrkp3OjOILxJO0P7JauHwnYIERh32EwDIigMe669PG81zIjFFLuaiNdpXfEjiZUNeKuwraOQmrnXiME1pLf0g8Ieta7M9tvKFQYTDTsehXct8z8LrCfTkykjfduX+rJytTcwXmBVsvGlW3FznFDeHC57eq5690oAc8+ca8qrvmm3Sa100ijcCCVBm8gt3yR/OX5hxC6OKF0wIig/SPqBlDMJlpZeZwDC5bnm50P51+vQBIJiGSez1J/q6/wHUZU9qoQtlbnczN2Hx9LaPEqUe4WzllGptWqeKIo401FzVnkI1jZYMAJf+6eO0buj6TIq/Mc6JC+BgJKSEdPipnAZHXmK24zyuTic4a4zjYpMNEmiCGvQ9HrT28uV+ku4/sHH0U1pKVx1H3lTygJOBMAAH1EtcOvFz2gWkCYc8JxE7pGzXzFGm5n1eqf+xp0Y7gR/f9pW3KmVmRaVkHYEZgTAyfOoZZhi544AgbHeT/QBhekOvEHfsaMtC11r1m4MXkDQLifaUw1UtuqyUjGA/21wW3fnNQ1xSlS41AVCXuX8bPKAZM/VjFWl/67KC8pjHMCXuHcfgZjL3FsquEANA=
